create or replace TABLE SNOWPIPE_DEMO.DWH_SCHEMA.DWH_CUSTOMER (
	ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 order,
	CUSTOMER_KEY NUMBER(38,0),
	FIRST_NAME VARCHAR(16777216),
	LAST_NAME VARCHAR(16777216),
	EMAIL VARCHAR(16777216),
	SIGNUP_DATE DATE,
	CREATED_DATE DATE,
	UPDATED_DATE DATE,
	primary key (ID)
);


create or replace TABLE SNOWPIPE_DEMO.DWH_SCHEMA.DWH_ORDER (
	ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 order,
	ORDER_KEY NUMBER(38,0),
	CUSTOMER_KEY NUMBER(38,0),
	ORDER_DATE DATE,
	TOTAL_AMOUNT NUMBER(10,2),
	CREATED_DATE DATE,
	UPDATED_DATE DATE,
	primary key (ID)
);


create or replace TABLE SNOWPIPE_DEMO.DWH_SCHEMA.DWH_ORDER_ITEM (
	ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 order,
	ORDER_ITEM_KEY NUMBER(38,0),
	ORDER_KEY NUMBER(38,0),
	PRODUCT_KEY NUMBER(38,0),
	QUANTITY NUMBER(38,0),
	UNIT_PRICE NUMBER(10,2),
	CREATED_DATE DATE,
	UPDATED_DATE DATE,
	primary key (ID)
);


create or replace TABLE SNOWPIPE_DEMO.DWH_SCHEMA.DWH_PAYMENT (
	ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 order,
	PAYMENT_KEY NUMBER(38,0),
	ORDER_KEY NUMBER(38,0),
	PAYMENT_DATE DATE,
	AMOUNT NUMBER(10,2),
	METHOD VARCHAR(16777216),
	CREATED_DATE DATE,
	UPDATED_DATE DATE,
	primary key (ID)
);


create or replace TABLE SNOWPIPE_DEMO.DWH_SCHEMA.DWH_PRODUCT (
	ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 order,
	PRODUCT_KEY NUMBER(38,0),
	PRODUCT_NAME VARCHAR(16777216),
	CATEGORY VARCHAR(16777216),
	PRICE NUMBER(10,2),
	CREATED_DATE DATE,
	UPDATED_DATE DATE,
	primary key (ID)
);