use databse snowpipe_demo;
use schema snowpipe_schema;


create or replace TABLE SNOWPIPE_DEMO.SNOWPIPE_SCHEMA.STG_CUSTOMER (
	CUSTOMER_KEY NUMBER(38,0) NOT NULL,
	FIRST_NAME VARCHAR(16777216),
	LAST_NAME VARCHAR(16777216),
	EMAIL VARCHAR(16777216),
	SIGNUP_DATE DATE,
	primary key (CUSTOMER_KEY)
);

create or replace TABLE SNOWPIPE_DEMO.SNOWPIPE_SCHEMA.STG_ORDER (
	ORDER_KEY NUMBER(38,0) NOT NULL,
	CUSTOMER_KEY NUMBER(38,0),
	ORDER_DATE DATE,
	TOTAL_AMOUNT NUMBER(10,2),
	primary key (ORDER_KEY)
);


create or replace TABLE SNOWPIPE_DEMO.SNOWPIPE_SCHEMA.STG_ORDER_ITEM (
	ORDER_ITEM_KEY NUMBER(38,0) NOT NULL,
	ORDER_KEY NUMBER(38,0),
	PRODUCT_KEY NUMBER(38,0),
	QUANTITY NUMBER(38,0),
	UNIT_PRICE NUMBER(10,2),
	primary key (ORDER_ITEM_KEY)
);


create or replace TABLE SNOWPIPE_DEMO.SNOWPIPE_SCHEMA.STG_PAYMENT (
	PAYMENT_KEY NUMBER(38,0) NOT NULL,
	ORDER_KEY NUMBER(38,0),
	PAYMENT_DATE DATE,
	AMOUNT NUMBER(10,2),
	METHOD VARCHAR(16777216),
	primary key (PAYMENT_KEY)
);



create or replace TABLE SNOWPIPE_DEMO.SNOWPIPE_SCHEMA.STG_PRODUCT (
	PRODUCT_KEY NUMBER(38,0) NOT NULL,
	PRODUCT_NAME VARCHAR(16777216),
	CATEGORY VARCHAR(16777216),
	PRICE NUMBER(10,2),
	primary key (PRODUCT_KEY)
);
